language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - "pypy"
before_install:
    - sudo pip install codecov
install:
    - pip install cffi
    - pip install python-coveralls
script:
    - python setup.py test
    - python setup.py install
    - coverage run --source=cmph setup.py test
    - coverage report -m
after_success:
    codecov
